Sprint2/step1
skvirl/react-burger pull request #3
Opened 2023-02-14 11:28 UTC by skvirl

2023-02-14 13:23 UTC, randomroot requested changes
**Доброго времени суток!** ☀️ 🌙 

Вы проделали очень хорошую работу по добавлению контекста в ваш проект, воспользовались хуком `useReducer`, написали практичные и полезные хуки, **так держать** 👍 

Тем не менее, для успешной сдачи работы вам необходимо внимательно ознакомиться с комментариями, оставленными в рамках ревью и провести необходимые **изменения**, обратив особое внимание на следующие моменты:

- При работе с редьюсером не следует **напрямую** взаимодействовать со `state`, создавайте её копию или копии её частей - важно соблюдать принцип "иммутабельности", что в дальнейшем будет критично для `Redux`;
- Cледует вынести **базовый адрес** сервера https://norma.nomoreparties.space/api сервера в отдельную константу, чтобы переиспользовать её в других урлах, т.к. эта часть не изменяется от запроса к запросу. 

Также, в рамках ревью были предложены **улучшения** вашего кода, которое могут повысить его качество, исправить возможные проблемы в будущем и углубить ваше значение по курсу.

---

Перед повторной сдачей, пожалуйста, убедитесь в том, что проект работает **корректно** и **полностью**, согласно условиям задания и чек-листу, а в консоли браузера и в консоли вашей IDE **нет ошибок** и присутствует **минимально** возможное кол-во **предупреждений**. Работа будет принята **только** после исправления всех комментариев с меткой "Надо исправить". 

---


**Успешного вам рефакторинга, хорошего настроения и отличного дня!** 🐈

2023-02-14 13:23 UTC, randomroot commented on src/hooks/useFetch.jsx
> +  const [data, setData] = React.useState([]);
🟡 **Можно улучшить:**

По-умолчанию лучше оставлять в поле `data` значение `null` т.к. в ответе могут быть не только массивы, но и объекты, а это может вызвать в дальнейшем проблемы с типизацией

2023-02-14 13:23 UTC, randomroot commented on src/utils/api.js
> +export const ingredientsApiUrl = "https://norma.nomoreparties.space/api/ingredients";
🔴 **Нужно исправить:**

Cледует вынести **базовый** адрес сервера `https://norma.nomoreparties.space/api` сервера в отдельную константу, чтобы переиспользовать её в других урлах, т.к. эта часть не изменяется от запроса к запросу. Плюс, если однажды бэкенд решит сменить урл, то вы сможете оперативно его поменять только в одном месте :)

2023-02-14 13:23 UTC, randomroot commented on src/index.tsx
> +  // <React.StrictMode>
🟡 **Можно улучшить:**

Не целесообразно отключать React.StrictMode из проекта, т.к. он помогает отслеживать возможные побочные эффекты про реализации ваших хуков и использовании встроенных, плюс напоминает о проблемах совместимости со старыми версиями Реакта. Поэтому, если возникают сложности только при его наличии, то в первую очередь лучше еще раз перепроверить код, а потом при крайне необходимости отключить "строгий режим"

2023-02-14 13:23 UTC, randomroot commented on src/utils/api.js
> +  if (res.ok) {
🟡 **Можно улучшить:**

Проверка ответа сервера и преобразование из json дублируется в нескольких местах, имеет смысл вынести их в отдельную функцию:

```
const checkReponse = (res) => {
  return res.ok ? res.json() : res.json().then((err) => Promise.reject(err));
};
```

2023-02-14 13:23 UTC, randomroot commented on src/components/Modal/OrderDetails.jsx
> +    executeApiRequest();
🟡 **Можно улучшить:**

Имеет смысл перенести процесс отправки заказа в конструктор, так как он отвечает за его сборку, а модальное окно оставить чисто для отображения его результата :)

2023-02-14 13:23 UTC, randomroot commented on src/components/BurgerConstructor/BurgerConstructor.jsx
> +            key={index}
🟡 **Можно улучшить:**

Обращаю ваше внимание, что в будущем следует заменить индекс на другое уникальное значение, т.к. текущий вариант не будет решать проблему ре-рендера при изменении элементов в конструкторе

2023-02-14 13:23 UTC, randomroot commented on src/hooks/useFetch.jsx
> +const useFetch = (requestFn) => {
🟢 **Отлично:**

Весьма практичный хук!

2023-02-14 13:23 UTC, randomroot commented on src/utils/context.js
> +         state.ingredients.push(action.ingredientId)
🔴 **Нужно исправить:**

В данном случае следует сначала создать копию массива, а только затем добавлять его элементы. Считайте, что `state` и его внутренности в режиме `read-only` и при изменении любой из его частей действия следует производить с его копией.

```js
  return { ...state, ingredients: [...ingredients, action.ingredientId] };
```

Аналогично ниже

2023-02-14 13:23 UTC, randomroot commented on src/utils/context.js
> +        if(existingIngredientIndex>=0) state.ingredients.splice(existingIngredientIndex,1);
🟡 **Можно улучшить:**

Удаление ID-шника из массива можно упростить с помощью функции `filter`, сразу создав копию:

```js
const newArr = arr.filter((val) => val !== action.ingredientId);
return { state, arr: newArr }
```

2023-02-14 17:33 UTC, skvirl commented on src/utils/context.js
> +        if(existingIngredientIndex>=0) state.ingredients.splice(existingIngredientIndex,1);
вот теперь когда там uuid можно и на фильтр упростить  :)

2023-02-14 17:33 UTC, skvirl commented on src/components/BurgerConstructor/BurgerConstructor.jsx
> +            key={index}
переделал массив элементов бургер конструктора с массива строк id ингридиентов на массив объектов {uuid, id ингридиента}. Заодно решил будущую проблему поэлементного удаления из него.

2023-02-15 08:19 UTC, randomroot approved these changes
🟢 **Работа принята:**

Все необходимые правки были внесены, код улучшен согласно рекомендациям, критических замечаний больше не имеется, **так держать**👍

_Обратите внимание на комментарий к файлу с редьюсером, чтобы лучше подготовиться к следующему спринту :)_

Отличная работа, **желаю вам хорошего дня и успехов в дальнейшем обучении**! 🐈

2023-02-15 08:19 UTC, randomroot commented on src/utils/context.js
> +        ingredients: [...state.ingredients, {constructorId:v4() ,_id:action.ingredientId}],
🟡 **Можно улучшить:**

В данном случае не критично, но в перспективе при переходе на `Redux` обратите внимание, что в самих редьюсерах не следует проводить генерацию идентификаторов, т.к. по задумке они являются "чистыми функциями" - т.е. функциями, которые при многократном вызове с одинаковым набором параметров всегда вернут одно и то же значение. В данном случае, это условие не соблюдается, т.к. `v4()` будет возвращать разные значения, поэтому подготовку данного идентификатора следует вести вне редьюсера

2023-02-15 10:29 UTC, skvirl commented on src/utils/context.js
> +        ingredients: [...state.ingredients, {constructorId:v4() ,_id:action.ingredientId}],
ауч! и правда...    Тогда буду вызывать в генераторе и передавать с экшеном. Спасибо! :)

2023-02-15 10:29 UTC, merged