Sprint4/step1
skvirl/react-burger pull request #6
Opened 2023-03-28 22:08 UTC by skvirl

2023-03-29 05:36 UTC, andryxxa93 requested changes
Здравствуйте! Отличная работа 👍 
Что понравилось:
- Хорошая типизация хуков
- Хорошо типизировали хранилище
- Типизировали утилитарные функции
- Практически не использовали `any`

Что необходимо исправить:
- Необходимо избавиться от кастований функций по типу `closeModal as unknown as MouseEventHandler`. Смотрите подробнее комментарий к `pull-request`.

Удачных правок!

2023-03-29 05:36 UTC, andryxxa93 commented on src/components/BunElem/BunElem.tsx
> +  const { ingredientData, selectedBunId } = useAppSelector((state) => ({
**Можно лучше**
Хорошая практика - передавать в useSelector не анонимную, а именованную функцию. Это позволит избежать лишних вызовов useSelector. 
https://www.youtube.com/watch?v=SVG-x-4BQic

2023-03-29 05:36 UTC, andryxxa93 commented on src/components/Modal/Modal.tsx
> +        <ModalOverlay closeModal={closeModal as unknown as MouseEventHandler} />
**Необходимо исправить**
Вот такие кастования признак того, что что-то в типизации было сделано неправильно. Дело в том, что тип `Function` как бы это странно не звучало, равносилен типу `any`. Он не даёт вообще никакого представления о том, что это за функция. Тут лучше использовать такой тип -  `closeModal: () => void`. Поправьте во всех подобных местах

2023-03-29 11:21 UTC, skvirl commented on src/components/Modal/Modal.tsx
> +        <ModalOverlay closeModal={closeModal as unknown as MouseEventHandler} />
о, круто! спасибо! Замена Funсtion на () => void позволило убрать as unknown. Не догадался что можно так просто обобщить функции зарытия.

2023-03-29 12:15 UTC, skvirl commented on src/components/BunElem/BunElem.tsx
> +  const { ingredientData, selectedBunId } = useAppSelector((state) => ({
больше бойлерплейта богу бойлерплейта  -_-

2023-03-29 18:59 UTC, andryxxa93 approved these changes
Супер, вы отлично поработали!
Поздравляю! Работа принята.
Желаю удачного продолжения обучения!
**Можно лучше**
И вы забыли поменять тип `closeModal` в `modalOverlay`. `as MouseEventHandler` тоже можно убрать в этом смысла уже нет.

2023-03-30 05:04 UTC, skvirl commented
Оу! Пропустил. Спасибо! )

2023-03-30 05:05 UTC, merged